wandb_version: 1

data:
  value: lang-model
data.preprocessing_num_workers:
  value: 20
data.version:
  value: original
eval.every:
  value: 5000
eval.iters:
  value: 1000
model:
  value: mamba
model.d_model:
  value: 800
model.max_seq_len:
  value: 512
model.n_layer:
  value: 8
optimizer:
  value: adamw
optimizer.lr:
  value: 0.000316228
optimizer.weight_decay:
  value: 0
save_checkpoints:
  value: true
scheduler.decay_lr:
  value: true
seed:
  value: 2059
train.batch_size:
  value: 50
train.do_early_stop:
  value: false
train.iters:
  value: 200001
train.log_every:
  value: 1000
train.num_workers:
  value: 0
train.parallel_loss:
  value: true
train.save_every:
  value: 50000
