wandb_version: 1

data:
  desc: null
  value: lang-model
data.preprocessing_num_workers:
  desc: null
  value: 20
data.version:
  desc: null
  value: original
eval.every:
  desc: null
  value: 5000
eval.iters:
  desc: null
  value: 1000
model:
  desc: null
  value: mamba
model.d_model:
  desc: null
  value: 800
model.max_seq_len:
  desc: null
  value: 512
model.n_layer:
  desc: null
  value: 8
optimizer:
  desc: null
  value: adamw
optimizer.lr:
  desc: null
  value: 0.000316228
optimizer.weight_decay:
  desc: null
  value: 0
save_checkpoints:
  desc: null
  value: true
scheduler.decay_lr:
  desc: null
  value: true
seed:
  desc: null
  value: 2059
train.batch_size:
  desc: null
  value: 50
train.do_early_stop:
  desc: null
  value: false
train.iters:
  desc: null
  value: 200001
train.log_every:
  desc: null
  value: 1000
train.num_workers:
  desc: null
  value: 0
train.parallel_loss:
  desc: null
  value: true
train.save_every:
  desc: null
  value: 50000
_wandb:
  desc: null
  value:
    python_version: 3.10.14
    cli_version: 0.15.9
    framework: huggingface
    huggingface_version: 4.32.1
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1717797776.975873
    t:
      1:
      - 1
      - 5
      - 9
      - 11
      - 41
      - 49
      - 50
      - 51
      - 53
      - 55
      - 63
      - 64
      2:
      - 1
      - 5
      - 9
      - 11
      - 41
      - 49
      - 50
      - 51
      - 53
      - 55
      - 63
      - 64
      3:
      - 1
      - 7
      - 23
      - 37
      4: 3.10.14
      5: 0.15.9
      6: 4.32.1
      8:
      - 5
    m:
    - 1: eval-eval.acc
      6:
      - 3
      7:
      - 2
    - 1: eval-train.acc
      6:
      - 3
      7:
      - 2
    - 1: eval-test.acc
      6:
      - 3
      7:
      - 2
    - 1: eval-eval.loss
      6:
      - 3
      7:
      - 1
    - 1: best_test_acc
      6:
      - 3
      7:
      - 2
    - 1: best_test_loss
      6:
      - 3
      7:
      - 1
    - 1: best_test_acc_train_iter
      6:
      - 3
      7:
      - 5
    - 1: best_test_loss_train_iter
      6:
      - 3
      7:
      - 5
    - 1: loss
      6:
      - 3
      7:
      - 1
seed_eval:
  desc: null
  value: 2000
seed_test:
  desc: null
  value: 3000
device:
  desc: null
  value: cuda
train:
  desc: null
  value:
    do: true
    do_save: false
    reset_every: null
    dtype: float32
    compile: false
    do_amp: false
    batch_size: 50
    grad_clip: 1.0
    iters: 200001
    samples: null
    log_every: 1000
    save_every: 50000
    save_path: ./out
    num_workers: 0
    do_early_stop: false
    early_stop_patience: 5
    early_stop_metric: loss
    early_stop_tol: 0.001
    early_stop_start_iter: 40000.200000000004
    early_stop_acc: null
    parallel_loss: true
    merge_embeds: false
    merge_type: sum
eval:
  desc: null
  value:
    do: true
    split: both
    batch_size: 1
    every: 5000
    every_samples: null
    iters: 1000
scheduler:
  desc: null
  value:
    decay_lr: true
    warmup_iters: 40000.200000000004
    lr_decay_iters: 200001
    min_lr: 3.16228e-05
log_level:
  desc: null
  value: info
examples_to_log:
  desc: null
  value: 3
log_batch_idx:
  desc: null
  value:
  - 0
  - 1
wandb:
  desc: null
  value:
    project: icl-arch
nl_icl:
  desc: null
  value:
    do: false
    checkpoint_path: null
    hf_path: null
    task: sentiment
    n_seeds: 10
    min_examples_per_class: 0
    max_examples_per_class: 9
    do_full_vocab: true
do_count_param_only:
  desc: null
  value: false
