wandb_version: 1

data:
  desc: null
  value: gauss-mix-model
data.dim:
  desc: null
  value: 16
data.num_classes:
  desc: null
  value: 2
data.num_xy_pairs_train:
  desc: null
  value: 32
data.num_xy_pairs_val:
  desc: null
  value: 1024
eval.every:
  desc: null
  value: 5000
eval.iters:
  desc: null
  value: 1000
model:
  desc: null
  value: mamba
model.d_model:
  desc: null
  value: 64
model.max_seq_len:
  desc: null
  value: 4096
model.n_layer:
  desc: null
  value: 12
optimizer:
  desc: null
  value: adamw
optimizer.betas:
  desc: null
  value:
  - 0.9
  - 0.95
optimizer.lr:
  desc: null
  value: 0.001
optimizer.weight_decay:
  desc: null
  value: 0
scheduler.decay_lr:
  desc: null
  value: true
seed:
  desc: null
  value: 5947
train.batch_size:
  desc: null
  value: 128
train.do_early_stop:
  desc: null
  value: false
train.iters:
  desc: null
  value: 100001
train.log_every:
  desc: null
  value: 1000
train.parallel_loss:
  desc: null
  value: true
_wandb:
  desc: null
  value:
    python_version: 3.10.14
    cli_version: 0.15.9
    framework: huggingface
    huggingface_version: 4.32.1
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1717683212.255513
    t:
      1:
      - 1
      - 5
      - 9
      - 11
      - 41
      - 49
      - 50
      - 51
      - 53
      - 55
      - 63
      - 64
      3:
      - 23
      4: 3.10.14
      5: 0.15.9
      6: 4.32.1
      8:
      - 5
