wandb_version: 1

data:
  value: omniglot
data.seq_config.p_bursty:
  value: 1
eval.every:
  value: 5000
eval.iters:
  value: 1000
model:
  value: mamba
model.d_model:
  value: 64
model.max_seq_len:
  value: 64
model.n_layer:
  value: 12
optimizer:
  value: adamw
optimizer.betas:
  value:
  - 0.9
  - 0.95
optimizer.lr:
  value: 0.000316228
optimizer.weight_decay:
  value: 0
scheduler.decay_lr:
  value: true
seed:
  value: 5947
train.batch_size:
  value: 128
train.do_early_stop:
  value: false
train.iters:
  value: 100001
train.log_every:
  value: 1000
train.num_workers:
  value: 4
train.parallel_loss:
  value: false
